server:
  port: 9008
  servlet:
    context-path: /demo
spring:
  redis:
    host: 192.168.38.138
    # ���ӳ�ʱʱ�䣨�ǵ���ӵ�λ��Duration��
    timeout: 10000ms
    # RedisĬ���������16����Ƭ���������þ���ʹ�õķ�Ƭ
    database: 0
    lettuce:
      pool:
        # ���ӳ������������ʹ�ø�ֵ��ʾû�����ƣ� Ĭ�� 8
        max-active: 8
        # ���ӳ���������ȴ�ʱ�䣨ʹ�ø�ֵ��ʾû�����ƣ� Ĭ�� -1
        max-wait: -1ms
        # ���ӳ��е����������� Ĭ�� 8
        max-idle: 8
        # ���ӳ��е���С�������� Ĭ�� 0
        min-idle: 0
    password: 123456
    port: 6379
  cache:
    # һ����˵�ǲ������õģ�Spring Cache ����������İ�����װ��
    type: redis
