
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    continue-on-error: true
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
logging:
  level:
    com.juejueguai: debug
    com..juejueguai.springbootdemomybatisplus.mapper: trace
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  #ʵ��ɨ�裬���package�ö��Ż��߷ֺŷָ�
  typeAliasesPackage: com.juejueguai.springbootdemomybatisplus.entity
  global-config:
    # ���ݿ��������
    db-config:
      #��������  AUTO:"���ݿ�ID����", INPUT:"�û�����ID",ID_WORKER:"ȫ��ΨһID (��������ΨһID)", UUID:"ȫ��ΨһID UUID";
      id-type: auto
      #�ֶβ��� IGNORED:"�����ж�",NOT_NULL:"�� NULL �ж�"),NOT_EMPTY:"�ǿ��ж�"
      field-strategy: not_empty
      #�շ��»���ת��
      table-underline: true
      #�Ƿ�����д������Ĭ�ϲ�����
      #capital-mode: true
      #�߼�ɾ������
      #logic-delete-value: 1
      #logic-not-delete-value: 0
      db-type: mysql
    #ˢ��mapper ��������
    refresh: true
  # ԭ������
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
server:
  port: 9004
